"""mobil to email

Revision ID: 9b3df0f71a6e
Revises: b8d4fba2d7d2
Create Date: 2018-10-21 18:25:56.963777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b3df0f71a6e'
down_revision = 'b8d4fba2d7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=32), nullable=True))
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
