"""init migration

Revision ID: b8d4fba2d7d2
Revises: 
Create Date: 2018-10-21 17:45:28.841551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8d4fba2d7d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=32), nullable=True))
    op.drop_index('email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
